### ISSUE TITLE
build fail on examples

### ISSUE THREAD

**Issue by amtrek** [pmem/libpmemobj-cpp#271]
All libraries should be installed, when trying to compile the examples, but I am getting errors on vector.hpp. I am using gcc 7.3.1 on centos 7, how do I fix this error ?

[  2%] Building CXX object tests/CMakeFiles/vector_range.dir/vector_range/vector_range.cpp.o
In file included from /home/labuser/Graftek/libpmemobj-cpp/tests/vector_range/vector_range.cpp:36:0:
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp: In lambda function:
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp:1715:26: error: parameter packs not expanded with ‘...’:
   tmp(std::forward<Args>(args)...);
                          ^
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp:1715:26: note:         ‘args’
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp: In lambda function:
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp:1774:43: error: parameter packs not expanded with ‘...’:
   construct(size(), 1, std::forward<Args>(args)...);
                                           ^
/home/labuser/PDME/libpmemobj-cpp/include/libpmemobj++/experimental/vector.hpp:1774:43: note:         ‘args’
make[2]: *** [tests/CMakeFiles/vector_range.dir/vector_range/vector_range.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/vector_range.dir/all] Error 2
make: *** [all] Error 2

**Comment by szyrom** [comment]
Hi amtrek,
C++11 allows for nested variadic function templates inside lambdas, however gcc 4.8.5 have a bug and following code won't compile:

```
template <typename... Args>
void boo(Args &&... args)
{
};

template <typename... Args>
void foo(Args &&... args)
{
    auto lambda = [&]{boo(std::forward<Args>(args)...);};
};

int main() {
    return 0;
}
```
but for gcc 7.3.1 it should compile. Can you double check if your gcc version is indeed 7.3.1 (it compiles with gcc 7.3.0 on my ubuntu 18.04)? 

If you want to use libpmemobj-cpp with gcc 4.8.5 you must resign from using our containers.
cmake options (enabled by default):
ENABLE_ARRAY
ENABLE_VECTOR
ENABLE_STRING
set to OFF will exclude containers headers.

**Comment by amtrek** [comment]
Hi, syzrom:

Thanks for reply, I double checked and my gcc version is 7.3.1. 
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

To help troubleshooing, here's my cmake output.

-- Found Perl: /bin/perl (found version "5.16.3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test CXX_HAS_/Zc:__cplusplus
-- Performing Test CXX_HAS_/Zc:__cplusplus - Failed
-- Checking for module 'libpmemobj>=1.4'
--   Found libpmemobj, version 1.4.2
-- Performing Test PMEMVLT_PRESENT
-- Performing Test PMEMVLT_PRESENT - Failed
CMake Warning at CMakeLists.txt:219 (message):
  pmemvlt support in libpmemobj not found (to enable - use libpmemobj version
  > 1.4


-- Performing Test NO_GCC_VARIADIC_TEMPLATE_BUG
-- Performing Test NO_GCC_VARIADIC_TEMPLATE_BUG - Failed
-- Performing Test NO_GCC_AGGREGATE_INITIALIZATION_BUG
-- Performing Test NO_GCC_AGGREGATE_INITIALIZATION_BUG - Failed
-- Performing Test NO_CLANG_BRACE_INITIALIZATION_NEWEXPR_BUG
-- Performing Test NO_CLANG_BRACE_INITIALIZATION_NEWEXPR_BUG - Success
-- Performing Test NO_CLANG_TEMPLATE_BUG
-- Performing Test NO_CLANG_TEMPLATE_BUG - Success
-- Performing Test NO_CHRONO_BUG
-- Performing Test NO_CHRONO_BUG - Success
-- Performing Test AGGREGATE_INITIALIZATION_AVAILABLE
-- Performing Test AGGREGATE_INITIALIZATION_AVAILABLE - Failed
-- Performing Test MAX_ALIGN_TYPE_EXISTS
-- Performing Test MAX_ALIGN_TYPE_EXISTS - Failed
-- Performing Test CXX_HAS__Wall
-- Performing Test CXX_HAS__Wall - Success
-- Performing Test CXX_HAS__Wpointer_arith
-- Performing Test CXX_HAS__Wpointer_arith - Success
-- Performing Test CXX_HAS__Wunused_macros
-- Performing Test CXX_HAS__Wunused_macros - Success
-- Performing Test CXX_HAS__Wsign_conversion
-- Performing Test CXX_HAS__Wsign_conversion - Success
-- Performing Test CXX_HAS__Wsign_compare
-- Performing Test CXX_HAS__Wsign_compare - Success
-- Performing Test CXX_HAS__Wunreachable_code_return
-- Performing Test CXX_HAS__Wunreachable_code_return - Failed
-- Performing Test CXX_HAS__Wmissing_variable_declarations
-- Performing Test CXX_HAS__Wmissing_variable_declarations - Failed
-- Performing Test CXX_HAS__fno_common
-- Performing Test CXX_HAS__fno_common - Success
-- Performing Test CXX_HAS__ggdb
-- Performing Test CXX_HAS__ggdb - Success
-- Performing Test CXX_HAS__DDEBUG
-- Performing Test CXX_HAS__DDEBUG - Success
-- Performing Test CXX_HAS__U_FORTIFY_SOURCE__D_FORTIFY_SOURCE_2
-- Performing Test CXX_HAS__U_FORTIFY_SOURCE__D_FORTIFY_SOURCE_2 - Success
CMake Warning at tests/ctest_helpers.cmake:192 (message):
  libunwind not found.  Stack traces from tests will not be reliable
Call Stack (most recent call first):
  tests/CMakeLists.txt:89 (find_packages)


CMake Warning at tests/ctest_helpers.cmake:212 (message):
  Valgrind not found.  Valgrind tests will not be performed.
Call Stack (most recent call first):
  tests/CMakeLists.txt:89 (find_packages)


CMake Warning at tests/CMakeLists.txt:108 (message):
  Skipping examples tests because of gcc variadic template bug


CMake Warning at tests/CMakeLists.txt:116 (message):
  Skipping aggregate initialization test because of no compiler support


CMake Warning at tests/CMakeLists.txt:177 (message):
  Skipping v test because no pmemvlt support found


CMake Warning at tests/CMakeLists.txt:246 (message):
  Skipping pmreorder tests because of no pmreorder support


-- Found Doxygen: /bin/doxygen (found version "1.8.5") 
CMake Warning at CMakeLists.txt:334 (message):
  Skipping build of examples because of compiler issue


-- Configuring done
-- Generating done
-- Build files have been written to: /home/labuser/Graftek/libpmemobj-cpp
[labuser@localhost libpmemobj-cpp]$ cmake .
CMake Warning at CMakeLists.txt:219 (message):
  pmemvlt support in libpmemobj not found (to enable - use libpmemobj version
  > 1.4


CMake Warning at tests/ctest_helpers.cmake:192 (message):
  libunwind not found.  Stack traces from tests will not be reliable
Call Stack (most recent call first):
  tests/CMakeLists.txt:89 (find_packages)


CMake Warning at tests/ctest_helpers.cmake:212 (message):
  Valgrind not found.  Valgrind tests will not be performed.
Call Stack (most recent call first):
  tests/CMakeLists.txt:89 (find_packages)


CMake Warning at tests/CMakeLists.txt:108 (message):
  Skipping examples tests because of gcc variadic template bug


CMake Warning at tests/CMakeLists.txt:116 (message):
  Skipping aggregate initialization test because of no compiler support


CMake Warning at tests/CMakeLists.txt:177 (message):
  Skipping v test because no pmemvlt support found


CMake Warning at tests/CMakeLists.txt:246 (message):
  Skipping pmreorder tests because of no pmreorder support


CMake Warning at CMakeLists.txt:334 (message):
  Skipping build of examples because of compiler issue


-- Configuring done
-- Generating done

**Comment by igchor** [comment]
Hi amtrek,

Could you please supply full CMake output?  I think you missed few lines from the beginning. The first line in the output should be "The C compiler identification is ...".

**Comment by amtrek** [comment]
Hi, igchor:

I was able to compile it after re-clone from repository as well so move to ubuntu18.04. Thanks for help.
